spring:
  data:
    mongodb:
      uri: mongodb+srv://gijin22:qIkwtBVNuVzPHOht@cluster0.uwirm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: blaybus

  security:
    user:
      name: admin
      password: 1234

  profiles:
    active: pay


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method