spring:
  data:
    mongodb:
      uri: mongodb://34.70.26.180:27017/
      database: blaybus
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "https://blaybus-glowup.com:8080/login/oauth2/code/google"

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

jwt:
  issuer: am030818@naver.com
  secret: "jfsgkhdsjkweoiruwqejkrfbhnsadkjlfghbwerqewrsdfgdsfagbdf"
  access-expiration: 3600
  refresh-expiration: 8640

server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:/keystore.p12
    key-store-password: blaybus
    key-store-type: PKCS12
    key-alias: blaybus