spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: blaybus
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#    mongodb:
#      uri: mongodb://34.70.26.180:27017/
#      database: blaybus